compiler = "gyc"
license = "GPL-v3"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
libraries = ["gmp", "mpfr"]
type = "library"
description = "Ymir bootstrap compiler"
version = "1.4.0"
name = "ymirc"
package-root="ymirc"

[std]
version = "1.3.5"
url = "git:https://github.com/GNU-Ymir/yruntime.git"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/bootstrap.git"

[commands]
set-version = { cmd = "./tools/set-version.sh", post = false }
