compiler = "gyc"
license = "GPL-v3"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
libraries = ["gmp", "mpfr"]
type = "library"
description = "Ymir bootstrap compiler"
version = "1.5.3"
name = "ymirc"
package-root="ymirc"
flags=["-O0"]

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/bootstrap.git"

[commands]
set-version = { cmd = "./tools/set-version.sh", post = false }
