#+title: Ymir language specification 1.0
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t _:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_HEADER: \usepackage[lmargin=0.5in, rmargin=0.5in]{geometry}


#+LATEX_HEADER: \usepackage{framed,color,verbatim}

#+LATEX_HEADER: \usepackage{minitoc}
#+LATEX_HEADER: \setcounter{minitocdepth}{5}

#+LATEX_HEADER: \definecolor{shadecolor}{rgb}{.9, .9, .9}
#+LATEX_HEADER: \newenvironment{code}{\footnotesize\snugshade\verbatim}{\endverbatim\endsnugshade\normalsize}

#+AUTHOR: Emile Cadorel

\dominitoc
\dominilof
\dominilot
\tableofcontents

* Document

** Ymir releases

Language specification of the Ymir language. This documentation is about the
language specification, but it is not a tutorial for the language.

The first stable version of ymir is the bootstraped version 1.0. It is defined to be buildable by the cxx_version (version 0.1 of the compiler written in c++). Associated tools (e.g. gyc, gyllir) the standard library and documentation are released with the same version as the language release. GYC has two different versions, the GCC version (such as 11.3.0) being the version of the backend and the version of the ymir language. Backend version should not have an impact on the behavior and only frontend version (ymirc version) has one.


** Syntax

This chapter presents the syntax specification of the ymir language. It is a
simplified grammar of the source code syntax. It was not verified whether the
grammar is complete, but it was made to be humanly readable, meaning that there
may be some inconsistencies. Improvements and verification would be evidently
greatly welcomed.

\minitoc
\pagebreak

#+INCLUDE: lexing/input.org

** Native types

This chapter presents semantic specification about native types and their
associated behavior. It lists the casting, binary, unary, index\ldots operators and
other allowed operations on the presented types. This chapter does not cover the
specifications on named custom types.

\minitoc
\pagebreak

#+INCLUDE: semantic/native_types.org
